### ISSUE TITLE
Crosshair shows as labeltext

### ISSUE THREAD

**Issue by Xeratone** [Hypnootize/TF2-Hud-Crosshairs#5]
![image](https://github.com/Hypnootize/TF2-HUD-Crosshairs/assets/44006352/07e73005-9026-401b-a297-b9e73d8ec9ad)\
![image](https://github.com/Hypnootize/TF2-HUD-Crosshairs/assets/44006352/391df2aa-8f27-4240-8973-83c04d189fd4)
![image](https://github.com/Hypnootize/TF2-HUD-Crosshairs/assets/44006352/88389ee1-91f8-47b1-a2e3-2d4443795a6e)
The above images are the lines I modified as the instructions say.

And the below image is what it looks like ingame:
![image](https://github.com/Hypnootize/TF2-HUD-Crosshairs/assets/44006352/9bf345e1-8ace-4605-87ad-1368afdecc1a)

**Comment by Hypnootize** [comment]
Seems like you are missing the `#base "../resource/crosshairs/crosshair_scheme.res"` inside the `ClientScheme.res`. 

It's the line responsible for the font installation and the related font entries, without it the game won't be able to find the crosshair font and will fallback to the default one, so instead of the actual crosshair it will display whatever the `LabelText` is.

**Comment by Xeratone** [comment]
> Seems like you are missing the `#base "../resource/crosshairs/crosshair_scheme.res"` inside the `ClientScheme.res`.
> 
> It's the line responsible for the font installation and the related font entries, without it the game won't be able to find the crosshair font and will fallback to the default one, so instead of the actual crosshair it will display whatever the `LabelText` is.

I tried this and it didn't work, however I reinstalled the whole thing and now it works, so I probably accidentally broke something in the configs the first time around.

**Comment by Xeratone** [comment]
> Seems like you are missing the `#base "../resource/crosshairs/crosshair_scheme.res"` inside the `ClientScheme.res`.
> 
> It's the line responsible for the font installation and the related font entries, without it the game won't be able to find the crosshair font and will fallback to the default one, so instead of the actual crosshair it will display whatever the `LabelText` is.

Question related to setup, is it possible to increase the size of the outline?

**Comment by Hypnootize** [comment]
No, sadly you can't as far as I'm aware.
