### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by UnderQuestion** [Hypnootize/TF2-Hud-Crosshairs#6]
after all steps crosshair doesnt appear on my screen in tf2

**Comment by Hypnootize** [comment]
I tried and it seems to be working fine for me. You want to download and extract the archive then take the `crosshairs` folder and move it inside your HUD's `resource` folder, then simply paste `#base "../resource/crosshairs/crosshair_scheme.res"` at the very start of your `ClientScheme.res` and `#base "../resource/Crosshairs/crosshair.res"` inside `HudLayout.res`. 

That should be enough to at least make the crosshair show up, you can then customize it from the crosshairs folder by editing the `crosshair.res` file.

Try checking if you did all the steps correctly, if you still can't get it to work take some screenshots of how you installed it and I'll check it out.

**Comment by UnderQuestion** [comment]
![Screenshot 2024-02-20 163138](https://github.com/Hypnootize/TF2-HUD-Crosshairs/assets/63191496/3bf4c685-efe2-40d3-8b8b-ae5d628cc3bf)
![Screenshot 2024-02-20 163158](https://github.com/Hypnootize/TF2-HUD-Crosshairs/assets/63191496/dd752c07-e1bf-4d5c-9ccd-f9113c9264a0)
![Screenshot 2024-02-20 163215](https://github.com/Hypnootize/TF2-HUD-Crosshairs/assets/63191496/a0850827-920b-474b-925b-60344352ac3f)

**Comment by UnderQuestion** [comment]
still doesnt work

**Comment by Hypnootize** [comment]
Looks to be installed correctly, what HUD are you trying to installed them in? is there any chance you are installing them in the default HUD and you are missing an `info.vdf` file? Might be a long shot but it's the only thing I can think of as of now.

**Comment by UnderQuestion** [comment]
yep thanks a lot. i ported info.vdf from your tf2defaulthud to my and everything started working.

**Comment by Hypnootize** [comment]
No problem, glad it works now!
